package:
  name: easyaccess
  version: "1.2.1b"

source:
  git_rev: '1.2.1b'
  git_url: https://github.com/mgckind/easyaccess
  

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - future
    - termcolor
    - fitsio
    - pandas >=0.14
    - oracle-instantclient
    - cx_oracle

test:
  # Python imports
  imports:
    - easyaccess

about:
  home: https://github.com/mgckind/easyaccess
  license: University of Illinois/NCSA Open Source License
  summary: 'Python command line interpreter to access DES Oracle database'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
