package:
  name: easyaccess
  version: "1.3.0rc"

source:
  fn: easyaccess-1.3.0-rc1.tar.gz
  md5: 9b6cbfd4630d0c55eb438509d4f3fd2e
  url: https://pypi.python.org/packages/aa/98/0e52eb2aff751936c9f37f28064a99b2d53271391681dcd977aa29076fa8/easyaccess-1.3.0-rc1.tar.gz
  #git_rev: '1.2.1b'
  #git_url: https://github.com/mgckind/easyaccess
  

build:
  number: 1


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - future
    - termcolor
    - fitsio
    - pandas >=0.14
    - oracle-instantclient
    - cx_oracle

test:
  # Python imports
  imports:
    - easyaccess

about:
  home: https://github.com/mgckind/easyaccess
  license: University of Illinois/NCSA Open Source License
  summary: 'Python command line interpreter to access DES Oracle database'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
